
services:
  app:
    container_name: netflix-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      -db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
    volumes:
    - :/code
    ports:
    - 8000:8000

  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
    - 5432:5432
    container_name: netflix-db
    volumes:
    - ./data/db/var/lib/postgresql/data