# Generated by Django 3.1.4 on 2021-06-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
