# Generated by Django 3.1.4 on 2021-06-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_actor_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='info',
        ),
        migrations.AddField(
            model_name='movie',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
