# Generated by Django 3.1.4 on 2021-06-29 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210629_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
