# Generated by Django 3.1.4 on 2021-07-17 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='birthdate',
        ),
    ]
