name: Movie API CD

on:
  push:
    branches: [master]

jobs:
  run_tests:
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODUL : netflix.settings
    steps:
      - uses: actions/chekout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Requairments
        run: pip install -r requairments.txt
      - name: Run Tests
        run: pytest

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: pip install poetry && poetry install
      - name: Run flake8
        run: git diff HEAD $(git merge-base HEAD origin/master)  | poetry run flake8 --diff
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} #hostyozliadi
          username: ${{ secrets.USERNAME }} #username yoziladi
          password: ${{ secrets.PASSWORD }} #password yoziladi
          port: ${{ secrets.PORT }} #port yoziladi
          script: |
            git pull
